export const  GET_EXERCICE_REQUEST ="GET_EXERCICE_REQUEST"
export const  GET_EXERCICE_SUCCESS ="GET_EXERCICE_SUCCESS"
export const  GET_EXERCICE_FAIL ="GET_EXERCICE_FAIL"

export const ADD_EXERCICE_REQUEST = "ADD_EXERCICE_REQUEST";
export const ADD_EXERCICE_SUCCESS = "ADD_EXERCICE_SUCCESS";
export const ADD_EXERCICE_FAIL =    "ADD_EXERCICE_FAIL";

export const UPDATE_EXERCICE_REQUEST = "UPDATE_EXERCICE_REQUEST";
export const UPDATE_EXERCICE_SUCCESS = "UPDATE_EXERCICE_SUCCESS";
export const UPDATE_EXERCICE_FAIL =    "UPDATE_EXERCICE_FAIL";