export const GET_ORGANISATION_REQUEST = "GET_ORGANISATION_REQUEST";
export const GET_ORGANISATION_SUCCESS = "GET_ORGANISATION_SUCCESS";
export const GET_ORGANISATION_FAIL = "GET_ORGANISATION_FAIL";

export const UPDATE_ORGANISATION_REQUEST = "UPDATE_ORGANISATION_REQUEST";
export const UPDATE_ORGANISATION_SUCCESS = "UPDATE_ORGANISATION_SUCCESS";
export const UPDATE_ORGANISATION_FAIL = "UPDATE_ORGANISATION_FAIL";
