export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL";

export const UPDATE_PASSWORD_USER_REQUEST = "UPDATE_PASSWORD_USER_REQUEST";
export const UPDATE_PASSWORD_USER_SUCCESS = "UPDATE_PASSWORD_USER_SUCCESS";
export const UPDATE_PASSWORD_USER_FAIL = "UPDATE_PASSWORD_USER_FAIL";

export const UPDATE_PHOTO_USER_REQUEST = "UPDATE_PHOTO_USER_REQUEST";
export const UPDATE_PHOTO_USER_SUCCESS = "UPDATE_PHOTO_USER_SUCCESS";
export const UPDATE_PHOTO_USER_FAIL = "UPDATE_PHOTO_USER_FAIL";
