
 export  const devisevalue = [
    { value: "AFN", label: "devise:LIST-DEVISE.AFGHANI"},
    { value: "AWG", label: "devise:LIST-DEVISE.ARUBAN-FLORIN" },
    { value: "AUD", label: "devise:LIST-DEVISE.AUSTRALIAN-DOLLAR" },
    { value: "AZN", label: "devise:LIST-DEVISE.AZERBAIJANIAN-MANAT" },
    { value: "THB", label: "devise:LIST-DEVISE.BAHT" },
    { value: "PAB", label: "devise:LIST-DEVISE.BALBOA" },
    { value: "ETB", label: "devise:LIST-DEVISE.BIRR-ÉTHIOPIENNE" },
    { value: "VEF", label: "devise:LIST-DEVISE.BOLIVAR" },
    { value: "BOB", label: "devise:LIST-DEVISE.BOLIVIANO" },
    { value: "BND", label: "devise:LIST-DEVISE.BRUNEI-DOLLAR" },
    { value: "CVE", label: "devise:LIST-DEVISE.CABO-VERDE-ESCUDO" },
    { value: "KYD", label: "devise:LIST-DEVISE.CAYMAN-ISLANDS-DOLLAR" },
    { value: "GHS", label: "devise:LIST-DEVISE.CEDI-DU-GHANA" },
    { value: "XOF", label: "devise:LIST-DEVISE.CFA-FRANC-BCEAO" },
    { value: "XAF", label: "devise:LIST-DEVISE.CFA-FRANC-BEAC" },
    { value: "NIO", label: "devise:LIST-DEVISE.CORDOBA" },
    { value: "CRC", label: "devise:LIST-DEVISE.CORDOBA" },
    { value: "DKK", label: "devise:LIST-DEVISE.COURONNE-DANOISE" },
    { value: "ISK", label: "devise:LIST-DEVISE.COURONNE-ISLANDAISE" },
    { value: "NOK", label: "devise:LIST-DEVISE.COURONNE-NORVÉGIENNE" },
    { value: "SEK", label: "devise:LIST-DEVISE.COURONNE-SUÉDOISE" },
    { value: "CZK", label: "devise:LIST-DEVISE.COURONNE-TCHÈQUE" },
    { value: "GMD", label: "devise:LIST-DEVISE.DALASI" },
    { value: "MKD", label: "devise:LIST-DEVISE.DENAR" },
    { value: "BHD", label: "devise:LIST-DEVISE.DINAR-BAHRAINI" },
    { value: "IQD", label: "devise:LIST-DEVISE.DINAR-IRAQUIEN" },
    { value: "KWD", label: "devise:LIST-DEVISE.DINAR-KOWAITIEN" },
    { value: "RSD", label: "devise:LIST-DEVISE.DINAR-SERBE" },
    { value: "DZD", label: "devise:LIST-DEVISE.DINARS-ALGÉRIENS" },
    { value: "JOD", label: "devise:LIST-DEVISE.DINARS-JORDANIEN" },
    { value: "LYD", label: "devise:LIST-DEVISE.DINARS-LIBIEN" },
    { value: "TND", label: "devise:LIST-DEVISE.DINARS-TUNISIENS" },
    { value: "MAD", label: "devise:LIST-DEVISE.DIRHAM-MAROCAIN" },
    { value: "MAD", label: "devise:LIST-DEVISE.DIRHAM-MAROCCAIN" },
    { value: "AED", label: "devise:LIST-DEVISE.DIRHAM-UAE" },
    { value: "STD", label: "devise:LIST-DEVISE.DOBRA" },
    { value: "AUD", label: "devise:LIST-DEVISE.DOLLAR-AUSTRALIEN" },
    { value: "BSD", label: "devise:LIST-DEVISE.DOLLAR-BAHAMÉEN" },
    { value: "BMD", label: "devise:LIST-DEVISE.DOLLAR-BERMUDIEN" },
    { value: "CAD", label: "devise:LIST-DEVISE.DOLLAR-CANADIEN" },
    { value: "BZD", label: "devise:LIST-DEVISE.DOLLAR-DE-BÉLIZE" },
    { value: "HKD", label: "devise:LIST-DEVISE.DOLLAR-DE-HONG-KONG" },
    {
      value: "XCD",
      label: "devise:LIST-DEVISE.DOLLAR-DES-CARAÏBES-ORIENTALES",
    },
    { value: "FJD", label: "devise:LIST-DEVISE.DOLLAR-DES-FIJI" },
    { value: "SBD", label: "devise:LIST-DEVISE.DOLLAR-DES-ÎLES-SOLOMON" },
    { value: "LRD", label: "devise:LIST-DEVISE.DOLLAR-DU-LIBERIA" },
    { value: "GYD", label: "devise:LIST-DEVISE.DOLLAR-GUYANIEN" },
    { value: "NAD", label: "devise:LIST-DEVISE.DOLLAR-NAMIBIEN" },
    { value: "NZD", label: "devise:LIST-DEVISE.DOLLAR-NÉO-ZÉLANDAIS" },
    { value: "SGD", label: "devise:LIST-DEVISE.DOLLAR-SINGAPORIEN" },
    { value: "USD", label: "devise:LIST-DEVISE.DOLLAR-US" },
    { value: "AUD", label: "devise:LIST-DEVISE.DOLLARS-AUSTRALIENS" },
    { value: "BBD", label: "devise:LIST-DEVISE.DOLLARS-BARBADOS" },
    {
      value: "TTD",
      label: "devise:LIST-DEVISE.DOLLARS-DE-TRINIDAD-ET-TOBAGO",
    },
    { value: "SRD", label: "devise:LIST-DEVISE.DOLLARS-DU-SURINAM" },
    { value: "ZWL", label: "devise:LIST-DEVISE.DOLLARS-DU-ZIMBABWE" },
    { value: "JMD", label: "devise:LIST-DEVISE.DOLLARS-JAMAICAIN" },
    { value: "DONG", label: "devise:LIST-DEVISE.DONG" },
    { value: "AMD", label: "devise:LIST-DEVISE.DRAM-ARMENIEN" },
    { value: "EUR", label: "devise:LIST-DEVISE.EURO" },
    {
      value: "ANG",
      label: "devise:LIST-DEVISE.FLORIN-DES-ANTILLES-NÉERLANDAISES",
    },
    { value: "HUF", label: "devise:LIST-DEVISE.FORINT" },
    { value: "BIF", label: "devise:LIST-DEVISE.FRANC-BURUNDI" },
    { value: "XOF", label: "devise:LIST-DEVISE.FRANC-CFA BCEAO" },
    { value: "XAF", label: "devise:LIST-DEVISE.FRANC-CFA BEAC" },
    { value: "XPF", label: "devise:LIST-DEVISE.FRANC-CFP" },
    { value: "KMF", label: "devise:LIST-DEVISE.FRANC-COMORIEN" },
    { value: "DJF", label: "devise:LIST-DEVISE.FRANC-DJIBOUTIEN" },
    { value: "GNF", label: "devise:LIST-DEVISE.FRANC-GUINÉEN" },
    { value: "RWF", label: "devise:LIST-DEVISE.FRANC-RWANDAIS" },
    { value: "CHF", label: "devise:LIST-DEVISE.FRANC-SUISSE" },
    { value: "CHW", label: "devise:LIST-DEVISE.FRANC-WIR" },
    { value: "HTG", label: "devise:LIST-DEVISE.GOURDE" },
    { value: "PYG", label: "devise:LIST-DEVISE.GUARANI" },
    { value: "UAH", label: "devise:LIST-DEVISE.HRYVNIA" },
    { value: "INR", label: "devise:LIST-DEVISE.INDIAN-RUPEE-INDIENNE" },
    { value: "PGK", label: "devise:LIST-DEVISE.KINA" },
    { value: "LAK", label: "devise:LIST-DEVISE.KIP" },
    { value: "HRK", label: "devise:LIST-DEVISE.KUNA" },
    { value: "MWK", label: "devise:LIST-DEVISE.KWACHA" },
    { value: "ZMW", label: "devise:LIST-DEVISE.KWACHA-ZAMBIEN" },
    { value: "AOA", label: "devise:LIST-DEVISE.KWANZA" },
    { value: "MMK", label: "devise:LIST-DEVISE.KYAT" },
    { value: "GEL", label: "devise:LIST-DEVISE.LARI" },
    { value: "SVC", label: "devise:LIST-DEVISE.LE-COLON-SALVADORIEN" },
    { value: "CDF", label: "devise:LIST-DEVISE.LE-FRANC-CONGOLAIS" },
    { value: "ALL", label: "devise:LIST-DEVISE.LEK" },
    { value: "HNL", label: "devise:LIST-DEVISE.LEMPIRA" },
    { value: "SLL", label: "devise:LIST-DEVISE.LEONE" },
    { value: "MDL", label: "devise:LIST-DEVISE.LEU-MOLDAVIEN" },
    { value: "RON", label: "devise:LIST-DEVISE.LEU-ROUMAIN" },
    { value: "BGN", label: "devise:LIST-DEVISE.LEV-BULGARE" },
    { value: "SZL", label: "devise:LIST-DEVISE.LILANGENI" },
    { value: "SHP", label: "devise:LIST-DEVISE.LIVRE-DE-SAINT-HELENE" },
    { value: "FKP", label: "devise:LIST-DEVISE.LIVRE-DES-ÎLES-MALOUINES" },
    { value: "SDG", label: "devise:LIST-DEVISE.LIVRE-SOUDANAIS" },
    { value: "GBP", label: "devise:LIST-DEVISE.LIVRE-STERLING" },
    { value: "GBP", label: "devise:LIST-DEVISE.LIVRE-STERLLING" },
    { value: "SSP", label: "devise:LIST-DEVISE.LIVRE-SUD-SOUDANAISE" },
    { value: "TRY", label: "devise:LIST-DEVISE.LIVRE-TURQUE" },
    { value: "LSL", label: "devise:LIST-DEVISE.LOTI" },
    { value: "MGA ", label: "devise:LIST-DEVISE.MALAGASY ARIARY" },
    { value: "BAM", label: "devise:LIST-DEVISE.MARK-CONVERTIBLE" },
    { value: "MUR", label: "devise:LIST-DEVISE.MAURITIUS-RUPEE" },
    { value: "MZN", label: "devise:LIST-DEVISE.METICAL" },
    {
      value: "MXV",
      label: "devise:LIST-DEVISE.MEXICAN-UNIDAD-DE-INVERSION-(UDI)",
    },
    { value: "BOV", label: "devise:LIST-DEVISE.MVDOL" },
    { value: "NGN", label: "devise:LIST-DEVISE.NAIRA" },
    { value: "ERN", label: "devise:LIST-DEVISE.NAKFA" },
    { value: "NZD", label: "devise:LIST-DEVISE.NÉO-ZÉLANDAIS" },
    { value: "BTN", label: "devise:LIST-DEVISE.NGULTRUM" },
    { value: "TWD", label: "devise:LIST-DEVISE.NOUVEAU-DOLLARS-TAIWANAIS" },
    { value: "ILS", label: "devise:LIST-DEVISE.NOUVEAU-SHEQEL-ISRAÉLIEN" },
    { value: "PEN", label: "devise:LIST-DEVISE.NOUVEAU-SOL" },
    { value: "MRO", label: "devise:LIST-DEVISE.OUGUIYA" },
    { value: "TOP", label: "devise:LIST-DEVISE.PA-ANGA" },
    { value: "0", label: "devise:LIST-DEVISE.PAS-DE-INTERNATIONALE" },
    { value: "0", label: "devise:LIST-DEVISE.PAS-DE-UNIVERSELLE" },
    { value: "MOP", label: "devise:LIST-DEVISE.PATACA" },
    { value: "ARS", label: "devise:LIST-DEVISE.PESO-ARGENTIN" },
    { value: "CLP", label: "devise:LIST-DEVISE.PESO-CHILIEN" },
    { value: "COP", label: "devise:LIST-DEVISE.PESO-COLOMBIEN" },
    { value: "CUC", label: "devise:LIST-DEVISE.PESO-CONVERTIBLE" },
    { value: "CUP", label: "devise:LIST-DEVISE.PESO-CUBAIN" },
    { value: "DOP", label: "devise:LIST-DEVISE.PESO-DOMINICAIN" },
    { value: "MXN", label: "devise:LIST-DEVISE.PESO-MEXICAIN" },
    { value: "PHP", label: "devise:LIST-DEVISE.PESO-PHILLIPINS" },
    { value: "UYU", label: "devise:LIST-DEVISE.PESO-URUGUAYEN" },
    { value: "GIP", label: "devise:LIST-DEVISE.POUND-DE-GIBRALTAR" },
    { value: "EGP", label: "devise:LIST-DEVISE.POUND-ÉGYPTIEN" },
    { value: "LBP", label: "devise:LIST-DEVISE.POUND-LIBANAIS" },
    { value: "SYP", label: "devise:LIST-DEVISE.POUND-SYRIEN" },
    { value: "BWP", label: "devise:LIST-DEVISE.PULA" },
    { value: "GTQ", label: "devise:LIST-DEVISE.QUETZAL" },
    { value: "ZAR", label: "devise:LIST-DEVISE.RAND" },
    { value: "BRL", label: "devise:LIST-DEVISE.REAL-BRÉSILIEN" },
    { value: "YER", label: "devise:LIST-DEVISE.RIAL-DU-YEMENL" },
    { value: "IRR", label: "devise:LIST-DEVISE.RIAL-IRANIEN" },
    { value: "OMR", label: "devise:LIST-DEVISE.RIAL-OMANI" },
    { value: "QAR", label: "devise:LIST-DEVISE.RIAL-QATARI" },
    { value: "KHR", label: "devise:LIST-DEVISE.RIEL" },
    { value: "MYR", label: "devise:LIST-DEVISE.RINGGI-MALAISIEN" },
    { value: "SAR", label: "devise:LIST-DEVISE.RIYAL-SAOUDIENS" },
    { value: "BYR", label: "devise:LIST-DEVISE.RUBLE-BIÉLORUSSE" },
    { value: "RUB", label: "devise:LIST-DEVISE.RUBLE-RUSSE" },
    { value: "MVR", label: "devise:LIST-DEVISE.RUFIYAA" },
    { value: "SCR", label: "devise:LIST-DEVISE.RUPEE-DES-SEYCHELLES" },
    { value: "PKR", label: "devise:LIST-DEVISE.RUPEE-DU-PAKISTAN" },
    { value: "INR", label: "devise:LIST-DEVISE.RUPEE-INDIENNE" },
    { value: "NPR", label: "devise:LIST-DEVISE.RUPEE-NÉPALAIS" },
    { value: "LKR", label: "devise:LIST-DEVISE.RUPEE-SRI-LANKAIS" },
    { value: "IDR", label: "devise:LIST-DEVISE.RUPIAH" },
    {
      value: "XDR",
      label: "devise:LIST-DEVISE.SDR-(DROIT-DE-TIRAGE-SPÉCIAL)",
    },
    { value: "KES", label: "devise:LIST-DEVISE.SHILLING-KENYAN" },
    { value: "UGX", label: "devise:LIST-DEVISE.SHILLING-OUGANDAISG" },
    { value: "SOS", label: "devise:LIST-DEVISE.SHILLING-SOMALIEN" },
    { value: "TZS", label: "devise:LIST-DEVISE.SHILLING-TANZANIEN" },
    { value: "KGS", label: "devise:LIST-DEVISE.SOM" },
    { value: "TJS", label: "devise:LIST-DEVISE.SOMONI" },
    { value: "XSU", label: "devise:LIST-DEVISE.SUCRE" },
    { value: "UZS", label: "devise:LIST-DEVISE.SUM-D'OUBEKISTAN" },
    { value: "CHF", label: "devise:LIST-DEVISE.SWISS-FRANC" },
    { value: "BDT", label: "devise:LIST-DEVISE.TAKA" },
    { value: "WST", label: "devise:LIST-DEVISE.TALA" },
    { value: "KZT", label: "devise:LIST-DEVISE.TENGE" },
    { value: "MNT", label: "devise:LIST-DEVISE.TUGRIK" },
    { value: "TMT", label: "devise:LIST-DEVISE.TURKMÉNISTAN-NOUVEAU-MANAT" },
    { value: "CLF", label: "devise:LIST-DEVISE.UNIDAD-DE-FOMENTO" },
    { value: "COU", label: "devise:LIST-DEVISE.UNIDAD-DE-VALOR-REAL" },
    { value: "XUA", label: "devise:LIST-DEVISE.UNITÉ-DE-COMPTE-DE-LA-BAD" },
    {
      value: "UYI",
      label: 
        "devise:LIST-DEVISE.URUGUAY-PESO-EN-UNIDADES-INDEXADAS-(URUIURUI)"
      ,
    },
    { value: "USD", label: "devise:LIST-DEVISE.US-DOLLAR" },
    { value: "VUV", label: "devise:LIST-DEVISE.VATU" },
    { value: "CHE", label: "devise:LIST-DEVISE.WIR-EURO" },
    { value: "KRW", label: "devise:LIST-DEVISE.WON" },
    { value: "KPW", label: "devise:LIST-DEVISE.WON-NORD-CORÉEN" },
    { value: "JPY", label: "devise:LIST-DEVISE.YEN" },
    { value: "CNY", label: "devise:LIST-DEVISE.YUAN-RENMINBI" },
    { value: "PLN", label: "devise:LIST-DEVISE.ZLOTY" },
  ];


